### ISSUE TITLE
api broken on deploy

### ISSUE THREAD

**Issue by ahdinosaur** [holodex/app#16]
[/groups/enspiral-craftworks](http://craftodex2.enspiral.info/api/groups/enspiral-craftworks)

```
root@craftodex:~# dokku logs craftodex2
Error: Requested Range Not Satisfiable
    at SendStream.error (/app/node_modules/serve-static/node_modules/send/index.js:239:16)
    at SendStream.send (/app/node_modules/serve-static/node_modules/send/index.js:533:19)
    at /app/node_modules/serve-static/node_modules/send/index.js:630:12
    at Object.oncomplete (fs.js:108:15)
Error: ENOENT, open '/app/data/groups/craftworks.yml'

/app/src/node_modules/fs-storage/index.js:116
          queue.push(this);
                ^
TypeError: Object #<Object> has no method 'push'
    at Object.<anonymous> (/app/src/node_modules/fs-storage/index.js:116:17)
    at null.<anonymous> (/app/src/node_modules/fs-storage/index.js:63:14)
    at fs.js:272:14
    at Object.oncomplete (fs.js:108:15)

npm ERR! craftodex@0.0.0 start: `node .`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the craftodex@0.0.0 start script.
npm ERR! This is most likely a problem with the craftodex package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node .
npm ERR! You can get their info via:
npm ERR!     npm owner ls craftodex
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.0-43-generic
npm ERR! command "/app/vendor/node/bin/node" "/app/vendor/node/bin/npm" "start"
npm ERR! cwd /app
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /app/npm-debug.log
npm ERR! not ok code 0

npm ERR! craftodex@0.0.0 prod: `NODE_ENV=production npm start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the craftodex@0.0.0 prod script.
npm ERR! This is most likely a problem with the craftodex package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_ENV=production npm start
npm ERR! You can get their info via:
npm ERR!     npm owner ls craftodex
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.0-43-generic
npm ERR! command "/app/vendor/node/bin/node" "/app/vendor/node/bin/npm" "run" "prod"
npm ERR! cwd /app
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /app/npm-debug.log
```

**Comment by ahdinosaur** [comment]
fixed with 22ec4540663d2f5c23a90d66b245fc7155f5b1a6 and 35f0b9622faf618b9edb33eea186d6f98cfd69f7.
